Dump nthreads
AppLayerLabs/bdk-cpp pull request #109
Opened 2024-05-09 16:31 UTC by lambdart

## Describe your changes

This pull request add threads to the state dump process,
first we verify how much threads are available and the
dump work is divided through them.

For this feature to work properly was necessary to remove some slices (pointers)
from the DB module to avoid use-after-free bug when DB operations batches
 are copied (on the thread) to a list (vector) of DB batches.

## Issue ticket number and link
 No ticket.

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update?
       If yes, please write one phrase about this update.

2024-05-11 15:56 UTC, Jean-Lessa requested changes

2024-05-11 15:56 UTC, Jean-Lessa commented on src/core/dump.cpp
Logic is good, only nitpick I have is the use of `auto`, I usually suggest being explicit with variable types so the code is more readable at first glance (as long as they're not excessively long by themselves, which is when using `auto` starts making sense, at least IMO). Given most if not all variables used here are inherently `unsigned int`s (judging by the use of `std::thread::hardware_concurrency()`), that could be a suitable replacement.

This is just a suggestion though, your call as to do it or not, the logic itself is pretty solid and will work like this anyway.

2024-05-11 15:56 UTC, Jean-Lessa commented on src/utils/db.cpp
Kinda the same thing here, it could be `const std::vector<DBEntry>& puts` and `const std::vector<Bytes>& dels`, but again it's just a nitpick, it should work either way.

2024-05-21 18:41 UTC, itamarcps approved these changes

2024-05-21 18:48 UTC, merged